import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  erpbridgeSidebar: [{type: 'autogenerated', dirName: 'erpbridge'}],
  bridgectlSidebar: [
    'bridgectl/overview',
    {
      type: 'category',
      label: 'API commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_api',
        'bridgectl/bridgectl_api_list',
        'bridgectl/bridgectl_api_register',
        'bridgectl/bridgectl_api_test',
      ],
    },
    {
      type: 'category',
      label: 'Tool commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_tool',
        'bridgectl/bridgectl_tool_apply',
        'bridgectl/bridgectl_tool_delete',
        'bridgectl/bridgectl_tool_describe',
        'bridgectl/bridgectl_tool_generate',
        'bridgectl/bridgectl_tool_get',
        'bridgectl/bridgectl_tool_validate',
      ],
    },
    {
      type: 'category',
      label: 'Cache commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_cache',
        'bridgectl/bridgectl_cache_flush',
        'bridgectl/bridgectl_cache_stats',
      ],
    },
    {
      type: 'category',
      label: 'Log commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_log',
        'bridgectl/bridgectl_log_stats',
        'bridgectl/bridgectl_log_tail',
      ],
    },
    {
      type: 'category',
      label: 'Context commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_context',
        'bridgectl/bridgectl_context_list',
        'bridgectl/bridgectl_context_set',
      ],
    },
    {
      type: 'category',
      label: 'Skill usage',
      collapsed: false,
      items: ['bridgectl/skills'],
    },
    {
      type: 'category',
      label: 'Other commands',
      collapsed: true,
      items: [
        'bridgectl/bridgectl_completion',
        'bridgectl/bridgectl_completion_bash',
        'bridgectl/bridgectl_completion_fish',
        'bridgectl/bridgectl_completion_powershell',
        'bridgectl/bridgectl_completion_zsh',
        'bridgectl/bridgectl_doc',
        'bridgectl/bridgectl_version',
      ],
    },
  ],
  roadmapSidebar: [{type: 'autogenerated', dirName: 'roadmap'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
};

export default sidebars;