import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  erpbridgeSidebar: [
    {
      type: 'category',
      label: 'ERPBridge Server',
      collapsed: false,
      items: [
        'erpbridge/intro',
        'erpbridge/quickstart',
        'erpbridge/onboarding',
        'erpbridge/connectivity',
        'erpbridge/agent-integrations',
        'erpbridge/transports',
        'erpbridge/console',
        'erpbridge/architecture',
        'erpbridge/tool-schema',
        'erpbridge/mcp-client-guide',
        'erpbridge/auth',
        'erpbridge/tokens',
        'erpbridge/docker',
        'erpbridge/environment-variables',
        'erpbridge/caching',
        'erpbridge/api',
        'erpbridge/mock-erp',
        'erpbridge/faq',
      ],
    },
    {
      type: 'category',
      label: 'Plugin integration and development',
      collapsed: false,
      items: [{ type: 'doc', id: 'erpbridge/plugins', label: 'External plugins and media adaptation' }],
    },
  ],
  bridgectlSidebar: [
    'bridgectl/overview',
    {
      type: 'category',
      label: 'Skill usage',
      collapsed: false,
      items: ['bridgectl/skills'],
    },
    {
      type: 'category',
      label: 'API commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_api',
        'bridgectl/bridgectl_api_list',
        'bridgectl/bridgectl_api_migrate-registry',
        'bridgectl/bridgectl_api_register',
        'bridgectl/bridgectl_api_scrub-credentials',
        'bridgectl/bridgectl_api_set-credential-ref',
        'bridgectl/bridgectl_api_test',
      ],
    },
    {
      type: 'category',
      label: 'Tool commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_tool',
        'bridgectl/bridgectl_tool_apply',
        'bridgectl/bridgectl_tool_delete',
        'bridgectl/bridgectl_tool_describe',
        'bridgectl/bridgectl_tool_generate',
        'bridgectl/bridgectl_tool_get',
        'bridgectl/bridgectl_tool_validate',
      ],
    },
    {
      type: 'category',
      label: 'Cache commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_cache',
        'bridgectl/bridgectl_cache_flush',
        'bridgectl/bridgectl_cache_stats',
      ],
    },
    {
      type: 'category',
      label: 'Log commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_log',
        'bridgectl/bridgectl_log_stats',
        'bridgectl/bridgectl_log_tail',
      ],
    },
    {
      type: 'category',
      label: 'Context commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_context',
        'bridgectl/bridgectl_context_list',
        'bridgectl/bridgectl_context_set',
      ],
    },
    {
      type: 'category',
      label: 'Token commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_token',
        'bridgectl/bridgectl_token_create',
        'bridgectl/bridgectl_token_list',
        'bridgectl/bridgectl_token_revoke',
      ],
    },
    {
      type: 'category',
      label: 'Skill commands',
      collapsed: false,
      items: [
        'bridgectl/bridgectl_skill',
        'bridgectl/bridgectl_skill_install',
      ],
    },
    {
      type: 'category',
      label: 'Other commands',
      collapsed: true,
      items: [
        'bridgectl/bridgectl_completion',
        'bridgectl/bridgectl_completion_bash',
        'bridgectl/bridgectl_completion_fish',
        'bridgectl/bridgectl_completion_powershell',
        'bridgectl/bridgectl_completion_zsh',
        'bridgectl/bridgectl_doc',
        'bridgectl/bridgectl_version',
        'bridgectl/bridgectl_web',
      ],
    },
  ],
  roadmapSidebar: [{type: 'autogenerated', dirName: 'roadmap'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
};

export default sidebars;
