import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  erpbridgeSidebar: [{type: 'autogenerated', dirName: 'erpbridge'}],
  roadmapSidebar: [{type: 'autogenerated', dirName: 'roadmap'}],
};

export default sidebars;
